### ISSUE TITLE
netty没用过啊

### ISSUE THREAD

**Issue by DaddySun51** [Sunnick/easy-im#1]
感觉像是代替socket的吧，websocket也是应该能代替的吧。

**Comment by Sunnick** [comment]
netty是用来做网络传输的。
通俗点说，就是基于TCP传输协议做数据传输。像Http、FTP、SMTP、POP3等协议都是建立在TCP协议之上的，netty都可以支持。当然，netty也支持UDP。netty还支持自定义协议，用起来比较方便
